name: Gradle Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set release version env variable
      run: echo "RELEASE_VERSION=$(./gradlew printVersion -q)" >> $GITHUB_ENV

    - name: Build and publish with Gradle
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
      run: ./gradlew package deploy

    - name: Deploy javadocs
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.JAVADOC_DEPLOY_KEY }}
        external_repository: lucyy-mc/javadocs
        publish_dir: ./target/site/apidocs
        destination_dir: lucycommonlib/${{ env.RELEASE_VERSION }}
