# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2i

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set Release version env variable
    run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: action-maven-publish
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        maven_goals_phases: "clean javadoc:javadoc deploy"
        nexus_username: ${{ secrets.REPO_USERNAME }}
        nexus_password: ${{ secrets.REPO_PASSWORD }}
        server_id: lucy
    - name: Deploy javadocs
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.JAVADOC_DEPLOY_KEY }}
        external_repository: lucyy-mc/javadocs
        publish_dir: ./target/site/apidocs
        destination_dir: lucycommonlib/${{ env.RELEASE_VERSION }}
